# Generated by Django 4.2.2 on 2024-01-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_network_networkdevice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='network_rating',
        ),
        migrations.AddField(
            model_name='comment',
            name='network_rating',
            field=models.ManyToManyField(related_name='comments', to='core.networkrating'),
        ),
    ]
