# Generated by Django 4.2.2 on 2024-01-25 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_comment_network_rating_comment_network_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkrating',
            name='device',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.networkdevice'),
        ),
    ]
