# Generated by Django 4.2.2 on 2024-01-25 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_networkrating_device_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkrating',
            name='network_device',
        ),
        migrations.AddField(
            model_name='networkrating',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.networkdevice'),
        ),
    ]
