# Generated by Django 4.2.2 on 2024-01-26 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_networkrating_network_device_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='network_rating',
        ),
        migrations.AddField(
            model_name='comment',
            name='network_rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.networkrating'),
        ),
    ]
